import type { DisputeStatus, TransactionStatus } from "../types/domain";

export const statusStyles: Record<TransactionStatus | DisputeStatus, string> = {
  completed: "border-[#C0C7D1] bg-[#E5E7EB] text-[#4B5563]",
  pending: "border-[#C0C7D1] bg-white text-[#4B5563]",
  review: "border-[#8A8F98] bg-[#E5E7EB] text-[#111827]",
  open: "border-[#8A8F98] bg-[#E5E7EB] text-[#111827]",
  resolved: "border-[#C0C7D1] bg-[#E5E7EB] text-[#4B5563]",
  escalated: "border-[#4B5563] bg-[#C0C7D1] text-[#111827]",
};

const benefits = [
  {
    title: "Risk signals surfaced early",
    text: "Spot suspicious payment patterns before they become disputes, losses, or compliance escalations.",
  },
  {
    title: "Case evidence in one place",
    text: "Give reviewers the transaction history, customer context, case reason, and next action in one view.",
  },
  {
    title: "Audit-ready decisions",
    text: "Keep status changes, evidence summaries, and reviewer actions ready for internal or regulatory review.",
  },
];

const quickLinks = ["Risk payment review", "Dispute evidence", "Audit-ready exports", "Human-led AI recommendations"];

const accountCards = [
  {
    title: "Payment Risk Review",
    text: "Prioritize suspicious transactions and move each case toward a clear, defensible decision.",
    action: "Review workflow",
  },
  {
    title: "Dispute Evidence Hub",
    text: "Bring notes, transaction details, and case status together so teams can act with confidence.",
    action: "View evidence",
  },
  {
    title: "Compliance Trail",
    text: "Keep every review step traceable for internal checks, handovers, and audit preparation.",
    action: "See audit trail",
  },
];

const serviceTiles = [
  "Request access",
  "Open payment review",
  "Check case status",
  "Analyze card activity",
  "Export evidence",
  "Contact a specialist",
];

const faqItems = [
  {
    question: "Who is FinGuard built for?",
    answer:
      "FinGuard is designed for digital banking, fintech, fraud, support, and compliance teams that need one workspace for risky payments, disputes, and review evidence.",
  },
  {
    question: "Does AI make the final decision?",
    answer:
      "No. AI is used as decision support. Reviewers can check customer history, transaction context, and dispute evidence before taking the final action.",
  },
  {
    question: "What evidence can teams export?",
    answer:
      "Teams can prepare transaction details, dispute reasons, case statuses, and evidence summaries for internal review or compliance checks.",
  },
];

export type Language = "en" | "uk" | "ru" | "es" | "it";

export const languageLabels: Record<Language, string> = {
  en: "EN",
  uk: "UA",
  ru: "RU",
  es: "ES",
  it: "IT",
};

export const content = {
  en: {
    topNav: ["Risk review", "Teams", "Support"],
    help: "Help centre",
    contact: "Contact info",
    tagline: "Secure banking intelligence",
    signedIn: "Signed in as",
    publicNav: {
      personal: "Payment review",
      business: "Teams",
      kids: "Evidence",
      company: "Company",
    },
    nav: {
      accounts: "Accounts",
      features: "Features",
      benefits: "Benefits",
      dashboard: "Review workspace",
      cabinet: "My cabinet",
      support: "Support",
    },
    auth: {
      login: "Log in",
      register: "Request access",
      createAccount: "Request access",
      secureAccess: "Secure access",
      newAccount: "Platform access",
      loginTitle: "Access FinGuard",
      registerTitle: "Create secure access",
      fullName: "Full name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm password",
      minPassword: "Minimum 6 characters",
      repeatPassword: "Repeat password",
      missingCredentials: "Please enter your email and password.",
      missingName: "Please enter your full name.",
      shortPassword: "Password must be at least 6 characters.",
      mismatch: "Passwords do not match.",
      demoAccess: "Guided access",
      fillDemo: "Fill",
    },
    profile: {
      accountOverview: "Account overview",
      settings: "Settings",
      signOut: "Sign out",
      profileSecurity: "Profile and security",
      notifications: "Notifications",
      riskAlerts: "Risk alerts",
      riskAlertsText: "Receive alerts when transactions move into review.",
      monthlySummary: "Monthly summary",
      monthlySummaryText: "Send a monthly account protection report.",
      securityChecks: "Security checks",
      securityChecksText: "Require extra verification for sensitive actions.",
      name: "Name",
      email: "Email",
      role: "Role",
      accounts: "Accounts",
      note: "These preferences are saved for this browser session and ready to sync with your secure workspace.",
      backToCabinet: "Back to cabinet",
      notAvailable: "Not available",
    },
    statusLabels: {
      pending: "Pending",
      completed: "Completed",
      review: "Review",
      open: "Open",
      resolved: "Resolved",
      escalated: "Escalated",
      active: "Active",
      frozen: "Frozen",
      closed: "Closed",
    },
    hero: {
      breadcrumb: "Home / Accounts / Protection",
      title: "Payment Risk Control",
      text:
        "FinGuard gives banking teams a secure review workspace for suspicious transactions, dispute evidence, and audit-ready decisions.",
      startDemo: "Request access",
      viewFeatures: "See workflow",
    },
    cabinet: {
      kicker: "My banking cabinet",
      titleSuffix: "'s account overview",
      text: "Accounts, recent transactions, and payment review cases are available in one secure workspace.",
      loading: "Loading account data",
      bankAccounts: "Bank accounts",
      currentAccount: "Current account",
      availableBalance: "Available balance",
      noAccounts: "No bank accounts were found for this user.",
      recentTransactions: "Recent transactions",
      viewAll: "View all",
      noTransactions: "No transactions yet.",
      reviewCases: "Review cases",
      open: "open",
    },
    accountsSection: {
      kicker: "Risk review without the chase",
      title: "Every payment, case, and evidence point in one review workspace",
      text: "Analysts see customer activity, transaction status, dispute reason, and next action without switching tools.",
    },
    featuresSection: {
      kicker: "Features and benefits",
      title: "Built for fraud, support, and compliance teams",
      text:
        "Move from alert to evidence-backed decision with consistent status tracking, human review, and exportable records.",
    },
    popular: {
      kicker: "Popular services",
      title: "What would you like to do today?",
    },
    cta: {
      kicker: "Why teams choose it",
      title: "Turn scattered payment checks into clear, defensible decisions.",
    },
    app: {
      quickActions: "Quick actions",
      addMoney: "Add money",
      transfer: "Transfer",
      cards: "Cards",
      analytics: "Analytics",
      mainAccount: "Main account",
      virtualCard: "Virtual card",
      cardReady: "Ready for secure online payments",
      spending: "Spending",
      thisMonth: "This month",
      protection: "Protection",
      protected: "Protected",
    },
    dashboard: {
      demoKicker: "Review workspace",
      userKicker: "User cabinet",
      demoTitle: "Account activity under review",
      userTitleSuffix: "'s banking overview",
      demoText: "Sign in to review accounts, transactions, and dispute cases in a secure workspace.",
      userText: "Review your bank accounts, recent transactions, and payment disputes in one secure workspace.",
      syncing: "Syncing",
      activeRecords: "active record(s)",
      opened: "Opened",
      transactions: "Transactions",
      transactionsHelp: "Search and filter account activity.",
      searchPlaceholder: "Search by transaction, status, or ID",
      transaction: "Transaction",
      time: "Time",
      amount: "Amount",
      status: "Status",
      noMatches: "No transactions match this search.",
      loginPrompt: "Log in to open your cabinet",
      loginPromptText:
        "The workspace shows accounts, transactions, and dispute cases for the signed-in reviewer.",
      sessionSecure: "Secure session",
      databaseConnected: "Database connected",
      apiReady: "API ready",
    },
    toast: {
      dismiss: "Dismiss",
      exportTitle: "Export ready",
      exportMessage: "Evidence CSV has been downloaded.",
      supportTitle: "Support opened",
      supportMessage: "Support questions are ready below.",
      actionTitle: "Action selected",
      statusTitle: "Status updated",
      demoStatusTitle: "Status updated",
      loginTitle: "Welcome back",
      registerTitle: "Access ready",
    },
    disputes: {
      title: "Dispute support",
      text: "Open a case to review evidence and update status.",
      export: "Export",
      create: "Create review case",
      transaction: "Transaction",
      choose: "Choose transaction",
      reason: "Reason",
      reasonPlaceholder: "Duplicate payment, unknown merchant...",
      createButton: "Create case",
      selected: "Selected case",
      account: "Account",
      currentStatus: "Current status",
      chooseError: "Choose a transaction and enter a short reason.",
      duplicateError: "This transaction already has a review case.",
      created: "New review case created",
      demoCreated: "Review case created",
      noCases: "No dispute cases yet.",
      openButton: "Open",
      escalateButton: "Escalate",
      resolveButton: "Resolve",
    },
    support: {
      kicker: "Need help?",
      title: "Clear answers for every case",
    },
    chat: {
      title: "FinGuard assistant",
      subtitle: "",
      welcome: "Hi, how can I help?",
      placeholder: "Ask about payments, disputes, or account monitoring...",
      send: "Send",
      thinking: "Assistant is checking this...",
      error: "The assistant is temporarily unavailable. Please try again.",
      close: "Close support chat",
    },
    cookie: {
      text: "This website uses",
      label: "cookies",
      accept: "Accept",
    },
    footer: {
      text: "An AI-assisted review workspace for secure payment monitoring, dispute support, and audit-ready evidence.",
      banking: "Banking",
      support: "Support",
      currentAccounts: "Current accounts",
      cards: "Cards",
      payments: "Payments",
      helpCentre: "Help centre",
      security: "Security",
      contact: "Contact",
      email: "support@finguard.app",
    },
    benefits,
    quickLinks,
    accountCards,
    serviceTiles,
    faqItems,
  },
  uk: {
    topNav: ["Приватним клієнтам", "Бізнесу", "Підтримка"],
    help: "Центр допомоги",
    contact: "Контактна інформація",
    tagline: "Безпечна банківська аналітика",
    signedIn: "Вхід виконано як",
    publicNav: {
      personal: "Приватним клієнтам",
      business: "Бізнесу",
      kids: "Дітям і підліткам",
      company: "Компанія",
    },
    nav: {
      accounts: "Акаунти",
      features: "Можливості",
      benefits: "Переваги",
      dashboard: "Review workspace",
      cabinet: "Мій кабінет",
      support: "Підтримка",
    },
    auth: {
      login: "Увійти",
      register: "Отримати доступ",
      createAccount: "Отримати доступ",
      secureAccess: "Безпечний доступ",
      newAccount: "Доступ до платформи",
      loginTitle: "Увійти у FinGuard",
      registerTitle: "Створити безпечний доступ",
      fullName: "Повне імʼя",
      email: "Email",
      password: "Пароль",
      confirmPassword: "Підтвердіть пароль",
      minPassword: "Мінімум 6 символів",
      repeatPassword: "Повторіть пароль",
      missingCredentials: "Введіть email і пароль.",
      missingName: "Введіть повне імʼя.",
      shortPassword: "Пароль має містити щонайменше 6 символів.",
      mismatch: "Паролі не збігаються.",
      demoAccess: "Швидкий доступ",
      fillDemo: "Заповнити",
    },
    profile: {
      accountOverview: "Огляд акаунта",
      settings: "Налаштування",
      signOut: "Вийти",
      profileSecurity: "Профіль і безпека",
      notifications: "Сповіщення",
      riskAlerts: "Ризикові операції",
      riskAlertsText: "Отримувати сповіщення, коли транзакції переходять на перевірку.",
      monthlySummary: "Місячний звіт",
      monthlySummaryText: "Надсилати щомісячний звіт із захисту акаунта.",
      securityChecks: "Перевірки безпеки",
      securityChecksText: "Вимагати додаткову перевірку для важливих дій.",
      name: "Імʼя",
      email: "Email",
      role: "Роль",
      accounts: "Акаунти",
      note: "Ці налаштування зберігаються для поточної сесії браузера та готові до синхронізації із захищеним workspace.",
      backToCabinet: "До кабінету",
      notAvailable: "Недоступно",
    },
    statusLabels: {
      pending: "Очікує",
      completed: "Завершено",
      review: "Перевірка",
      open: "Відкрита",
      resolved: "Закрита",
      escalated: "Ескальована",
      active: "Активний",
      frozen: "Заморожений",
      closed: "Закритий",
    },
    hero: {
      breadcrumb: "Головна / Акаунти / Захист",
      title: "Контроль ризикових платежів",
      text:
        "FinGuard дає банківським командам захищений простір для підозрілих транзакцій, доказів по спорах і рішень, готових до аудиту.",
      startDemo: "Отримати доступ",
      viewFeatures: "Переглянути процес",
    },
    cabinet: {
      kicker: "Мій банківський кабінет",
      titleSuffix: ": огляд акаунта",
      text: "Акаунти, останні транзакції та заявки на перевірку доступні в одному захищеному workspace.",
      loading: "Завантаження даних",
      bankAccounts: "Банківські акаунти",
      currentAccount: "Поточний акаунт",
      availableBalance: "Доступний баланс",
      noAccounts: "Для цього користувача не знайдено банківських акаунтів.",
      recentTransactions: "Останні транзакції",
      viewAll: "Дивитися всі",
      noTransactions: "Транзакцій ще немає.",
      reviewCases: "Заявки на перевірку",
      open: "відкрито",
    },
    accountsSection: {
      kicker: "Перевірка без зайвого пошуку",
      title: "Платежі, заявки й докази в одному робочому просторі",
      text: "Аналітики бачать активність клієнта, статус транзакції, причину спору та наступну дію без перемикання між інструментами.",
    },
    featuresSection: {
      kicker: "Можливості та переваги",
      title: "Для fraud, support і compliance-команд",
      text:
        "Переходьте від сигналу ризику до рішення з доказами: статуси, ручна перевірка, історія справи та експортовані записи в одному місці.",
    },
    popular: {
      kicker: "Популярні сервіси",
      title: "Що ви хочете зробити сьогодні?",
    },
    cta: {
      kicker: "Чому команди обирають це",
      title: "Перетворіть розрізнені перевірки платежів на чіткі рішення з доказами.",
    },
    app: {
      quickActions: "Швидкі дії",
      addMoney: "Поповнити",
      transfer: "Переказ",
      cards: "Картки",
      analytics: "Аналітика",
      mainAccount: "Головний акаунт",
      virtualCard: "Віртуальна картка",
      cardReady: "Готова для безпечних онлайн-платежів",
      spending: "Витрати",
      thisMonth: "Цього місяця",
      protection: "Захист",
      protected: "Захищено",
    },
    dashboard: {
      demoKicker: "Робочий простір перевірки",
      userKicker: "Кабінет користувача",
      demoTitle: "Активність акаунта на перевірці",
      userTitleSuffix: ": банківський огляд",
      demoText: "Увійдіть, щоб працювати з акаунтами, транзакціями та заявками в захищеному просторі.",
      userText: "Переглядайте банківські акаунти, останні транзакції та спірні платежі в одному захищеному просторі.",
      syncing: "Синхронізація",
      activeRecords: "активних записів",
      opened: "Відкрито",
      transactions: "Транзакції",
      transactionsHelp: "Пошук і фільтрація активності акаунта.",
      searchPlaceholder: "Пошук за транзакцією, статусом або ID",
      transaction: "Транзакція",
      time: "Час",
      amount: "Сума",
      status: "Статус",
      noMatches: "Немає транзакцій за цим пошуком.",
      loginPrompt: "Увійдіть, щоб відкрити кабінет",
      loginPromptText:
        "Workspace показує акаунти, транзакції та заявки для користувача, який увійшов у систему.",
      sessionSecure: "Безпечна сесія",
      databaseConnected: "База підключена",
      apiReady: "API готовий",
    },
    toast: {
      dismiss: "Закрити",
      exportTitle: "Експорт готовий",
      exportMessage: "CSV з доказами завантажено.",
      supportTitle: "Підтримку відкрито",
      supportMessage: "Питання підтримки доступні нижче.",
      actionTitle: "Дію обрано",
      statusTitle: "Статус оновлено",
      demoStatusTitle: "Статус оновлено",
      loginTitle: "Вітаємо знову",
      registerTitle: "Доступ готовий",
    },
    disputes: {
      title: "Підтримка заявок",
      text: "Відкрийте справу, щоб перевірити докази та оновити статус.",
      export: "Експорт",
      create: "Створити заявку",
      transaction: "Транзакція",
      choose: "Оберіть транзакцію",
      reason: "Причина",
      reasonPlaceholder: "Подвійний платіж, невідомий продавець...",
      createButton: "Створити",
      selected: "Обрана заявка",
      account: "Акаунт",
      currentStatus: "Поточний статус",
      chooseError: "Оберіть транзакцію і введіть коротку причину.",
      duplicateError: "Ця транзакція вже має заявку на перевірку.",
      created: "Нову заявку створено",
      demoCreated: "Заявку створено",
      noCases: "Заявок ще немає.",
      openButton: "Відкрити",
      escalateButton: "Ескалювати",
      resolveButton: "Закрити",
    },
    support: {
      kicker: "Потрібна допомога?",
      title: "Зрозумілі відповіді для кожної справи",
    },
    chat: {
      title: "Асистент FinGuard",
      subtitle: "",
      welcome:
        "Вітаю, я допоможу з акаунтами, транзакціями, заявками на перевірку та роботою кабінету FinGuard.",
      placeholder: "Запитайте про платежі, спори або моніторинг акаунту...",
      send: "Надіслати",
      thinking: "Асистент перевіряє запит...",
      error: "Асистент тимчасово недоступний. Спробуйте ще раз.",
      close: "Закрити чат підтримки",
    },
    cookie: {
      text: "Цей сайт використовує",
      label: "cookies",
      accept: "Прийняти",
    },
    footer: {
      text: "AI-workspace для моніторингу платежів, підтримки спорів і підготовки доказів до аудиту.",
      banking: "Банкінг",
      support: "Підтримка",
      currentAccounts: "Поточні акаунти",
      cards: "Картки",
      payments: "Платежі",
      helpCentre: "Центр допомоги",
      security: "Безпека",
      contact: "Контакти",
      email: "support@finguard.app",
    },
    benefits: [
      {
        title: "Ризикові сигнали раніше",
        text: "Виявляйте підозрілі платіжні патерни до того, як вони стануть спором, збитком або compliance-ескалацією.",
      },
      {
        title: "Докази справи в одному місці",
        text: "Дайте reviewerʼам історію транзакцій, контекст клієнта, причину заявки та наступну дію в одному перегляді.",
      },
      {
        title: "Рішення, готові до аудиту",
        text: "Зберігайте зміни статусів, evidence summaries і дії спеціалістів для внутрішніх або регуляторних перевірок.",
      },
    ],
    quickLinks: ["Перевірка ризикових платежів", "Докази по спорах", "Експорт для аудиту", "AI-рекомендації під контролем людини"],
    accountCards: [
      {
        title: "Перевірка ризикових платежів",
        text: "Пріоритизуйте підозрілі транзакції та доводьте кожну справу до чіткого рішення з доказами.",
        action: "Переглянути процес",
      },
      {
        title: "Центр доказів по спорах",
        text: "Обʼєднуйте нотатки, деталі транзакції та статус справи, щоб команда діяла впевнено.",
        action: "Переглянути докази",
      },
      {
        title: "Compliance trail",
        text: "Зберігайте кожен крок перевірки для handover, внутрішнього контролю та підготовки до аудиту.",
        action: "Переглянути audit trail",
      },
    ],
    serviceTiles: ["Отримати доступ", "Відкрити перевірку платежу", "Перевірити статус справи", "Проаналізувати карткову активність", "Експортувати докази", "Звʼязатися зі спеціалістом"],
    faqItems: [
      {
        question: "Для кого створено FinGuard?",
        answer:
          "FinGuard створено для digital banking, fintech, fraud, support і compliance-команд, яким потрібен один простір для ризикових платежів, спорів і доказів.",
      },
      {
        question: "Чи ухвалює AI фінальне рішення?",
        answer:
          "Ні. AI працює як підтримка для рішення. Спеціаліст перевіряє історію клієнта, контекст транзакції та докази перед фінальною дією.",
      },
      {
        question: "Які докази можна підготувати для аудиту?",
        answer:
          "Команда може підготувати деталі транзакцій, причини заявок, статуси справ і evidence summaries для внутрішньої або compliance-перевірки.",
      },
    ],
  },
};

export type Content = typeof content.en;

export const localizedContent: Record<Language, Content> = {
  en: content.en,
  uk: content.uk,
  ru: {
    ...content.en,
    topNav: ["Риски", "Команды", "Поддержка"],
    help: "Центр помощи",
    contact: "Контактная информация",
    tagline: "Безопасная банковская аналитика",
    signedIn: "Вход выполнен как",
    publicNav: {
      personal: "Проверка платежей",
      business: "Команды",
      kids: "Доказательства",
      company: "Компания",
    },
    nav: {
      accounts: "Счета",
      features: "Возможности",
      benefits: "Преимущества",
      dashboard: "Пространство проверки",
      cabinet: "Кабинет",
      support: "Поддержка",
    },
    auth: {
      ...content.en.auth,
      login: "Войти",
      register: "Получить доступ",
      createAccount: "Получить доступ",
      loginTitle: "Войти в FinGuard",
      registerTitle: "Создать безопасный доступ",
      password: "Пароль",
      confirmPassword: "Подтвердите пароль",
    },
    profile: {
      ...content.en.profile,
      accountOverview: "Обзор аккаунта",
      settings: "Настройки",
      signOut: "Выйти",
      profileSecurity: "Профиль и безопасность",
      notifications: "Уведомления",
      note: "Эти настройки сохраняются для текущей сессии браузера и готовы к синхронизации с защищенным workspace.",
      name: "Имя",
      role: "Роль",
      accounts: "Счета",
      backToCabinet: "К кабинету",
    },
    toast: {
      ...content.en.toast,
      loginTitle: "С возвращением",
      registerTitle: "Доступ готов",
    },
    app: {
      ...content.en.app,
      quickActions: "Быстрые действия",
      addMoney: "Пополнить",
      transfer: "Перевод",
      cards: "Карты",
      analytics: "Аналитика",
      mainAccount: "Основной счет",
      virtualCard: "Виртуальная карта",
      cardReady: "Готова для безопасных онлайн-платежей",
      spending: "Расходы",
      protection: "Защита",
      protected: "Защищено",
    },
    cabinet: {
      ...content.en.cabinet,
      kicker: "Рабочее пространство",
      titleSuffix: ": обзор проверок",
      text: "Счета, последние транзакции и заявки на проверку доступны в одном защищенном workspace.",
      loading: "Загрузка данных",
      bankAccounts: "Счета",
      recentTransactions: "Последние транзакции",
      reviewCases: "Заявки на проверку",
      viewAll: "Все",
    },
    dashboard: {
      ...content.en.dashboard,
      transactions: "Транзакции",
      searchPlaceholder: "Поиск по транзакции, статусу или ID",
      sessionSecure: "Безопасная сессия",
      databaseConnected: "База подключена",
      apiReady: "API готов",
    },
    statusLabels: {
      pending: "Ожидает",
      completed: "Завершено",
      review: "Проверка",
      open: "Открыта",
      resolved: "Закрыта",
      escalated: "Эскалация",
      active: "Активен",
      frozen: "Заморожен",
      closed: "Закрыт",
    },
    disputes: {
      ...content.en.disputes,
      title: "Поддержка заявок",
      create: "Создать заявку",
      choose: "Выберите транзакцию",
      reason: "Причина",
      createButton: "Создать",
      export: "Экспорт",
    },
    cookie: {
      text: "Этот сайт использует",
      label: "cookies",
      accept: "Принять",
    },
  },
  es: {
    ...content.en,
    topNav: ["Riesgo", "Equipos", "Soporte"],
    help: "Centro de ayuda",
    contact: "Información de contacto",
    tagline: "Inteligencia bancaria segura",
    signedIn: "Sesión iniciada como",
    publicNav: {
      personal: "Revisión de pagos",
      business: "Equipos",
      kids: "Evidencia",
      company: "Company",
    },
    nav: {
      accounts: "Cuentas",
      features: "Funciones",
      benefits: "Ventajas",
      dashboard: "Área de revisión",
      cabinet: "Mi cuenta",
      support: "Soporte",
    },
    auth: {
      ...content.en.auth,
      login: "Entrar",
      register: "Solicitar acceso",
      createAccount: "Solicitar acceso",
      loginTitle: "Entrar en FinGuard",
      registerTitle: "Crear acceso seguro",
      password: "Contraseña",
      confirmPassword: "Confirmar contraseña",
    },
    profile: {
      ...content.en.profile,
      accountOverview: "Resumen de cuenta",
      settings: "Ajustes",
      signOut: "Salir",
      profileSecurity: "Perfil y seguridad",
      notifications: "Notificaciones",
      note: "Estas preferencias se guardan para esta sesión del navegador y están listas para sincronizarse con tu espacio seguro.",
      name: "Nombre",
      role: "Rol",
      accounts: "Cuentas",
      backToCabinet: "Volver al panel",
    },
    toast: {
      ...content.en.toast,
      loginTitle: "Bienvenido de nuevo",
      registerTitle: "Acceso listo",
    },
    app: {
      ...content.en.app,
      quickActions: "Acciones rápidas",
      addMoney: "Añadir dinero",
      transfer: "Transferir",
      cards: "Tarjetas",
      analytics: "Analítica",
      mainAccount: "Cuenta principal",
      virtualCard: "Tarjeta virtual",
      cardReady: "Lista para pagos online seguros",
      spending: "Gastos",
      protection: "Protección",
      protected: "Protegido",
    },
    cabinet: {
      ...content.en.cabinet,
      kicker: "Espacio de revisión",
      titleSuffix: ": resumen de revisión",
      text: "Cuentas, transacciones recientes y casos de revisión están disponibles en un espacio seguro.",
      loading: "Cargando datos",
      bankAccounts: "Cuentas",
      recentTransactions: "Transacciones recientes",
      reviewCases: "Casos de revisión",
      viewAll: "Ver todo",
    },
    dashboard: {
      ...content.en.dashboard,
      transactions: "Transacciones",
      searchPlaceholder: "Buscar por transacción, estado o ID",
      sessionSecure: "Sesión segura",
      databaseConnected: "Base conectada",
      apiReady: "API lista",
    },
    statusLabels: {
      pending: "Pendiente",
      completed: "Completado",
      review: "Revisión",
      open: "Abierto",
      resolved: "Resuelto",
      escalated: "Escalado",
      active: "Activo",
      frozen: "Bloqueado",
      closed: "Cerrado",
    },
    disputes: {
      ...content.en.disputes,
      title: "Soporte de disputas",
      create: "Crear caso",
      choose: "Elegir transacción",
      reason: "Motivo",
      createButton: "Crear",
      export: "Exportar",
    },
    cookie: {
      text: "Este sitio usa",
      label: "cookies",
      accept: "Aceptar",
    },
  },
  it: {
    ...content.en,
    topNav: ["Rischio", "Team", "Supporto"],
    help: "Centro assistenza",
    contact: "Info contatto",
    tagline: "Intelligenza bancaria sicura",
    signedIn: "Accesso come",
    publicNav: {
      personal: "Revisione pagamenti",
      business: "Team",
      kids: "Evidenze",
      company: "Company",
    },
    nav: {
      accounts: "Conti",
      features: "Funzioni",
      benefits: "Vantaggi",
      dashboard: "Area di revisione",
      cabinet: "Area personale",
      support: "Supporto",
    },
    auth: {
      ...content.en.auth,
      login: "Accedi",
      register: "Richiedi accesso",
      createAccount: "Richiedi accesso",
      loginTitle: "Accedi a FinGuard",
      registerTitle: "Crea accesso sicuro",
      password: "Password",
      confirmPassword: "Conferma password",
    },
    profile: {
      ...content.en.profile,
      accountOverview: "Panoramica account",
      settings: "Impostazioni",
      signOut: "Esci",
      profileSecurity: "Profilo e sicurezza",
      notifications: "Notifiche",
      note: "Queste preferenze vengono salvate per questa sessione del browser e sono pronte per la sincronizzazione con lo spazio sicuro.",
      name: "Nome",
      role: "Ruolo",
      accounts: "Conti",
      backToCabinet: "Torna all'area",
    },
    toast: {
      ...content.en.toast,
      loginTitle: "Bentornato",
      registerTitle: "Accesso pronto",
    },
    app: {
      ...content.en.app,
      quickActions: "Azioni rapide",
      addMoney: "Aggiungi fondi",
      transfer: "Trasferisci",
      cards: "Carte",
      analytics: "Analisi",
      mainAccount: "Conto principale",
      virtualCard: "Carta virtuale",
      cardReady: "Pronta per pagamenti online sicuri",
      spending: "Spese",
      protection: "Protezione",
      protected: "Protetto",
    },
    cabinet: {
      ...content.en.cabinet,
      kicker: "Area di revisione",
      titleSuffix: ": panoramica revisioni",
      text: "Conti, transazioni recenti e casi di revisione sono disponibili in uno spazio sicuro.",
      loading: "Caricamento dati",
      bankAccounts: "Conti",
      recentTransactions: "Transazioni recenti",
      reviewCases: "Casi di revisione",
      viewAll: "Vedi tutto",
    },
    dashboard: {
      ...content.en.dashboard,
      transactions: "Transazioni",
      searchPlaceholder: "Cerca per transazione, stato o ID",
      sessionSecure: "Sessione sicura",
      databaseConnected: "Database connesso",
      apiReady: "API pronta",
    },
    statusLabels: {
      pending: "In attesa",
      completed: "Completato",
      review: "Revisione",
      open: "Aperto",
      resolved: "Risolto",
      escalated: "Escalation",
      active: "Attivo",
      frozen: "Bloccato",
      closed: "Chiuso",
    },
    disputes: {
      ...content.en.disputes,
      title: "Supporto contestazioni",
      create: "Crea caso",
      choose: "Scegli transazione",
      reason: "Motivo",
      createButton: "Crea",
      export: "Esporta",
    },
    cookie: {
      text: "Questo sito usa",
      label: "cookies",
      accept: "Accetta",
    },
  },
};
